import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Facility, FacilityResponse } from '../Facility';
import { Observable, of, throwError } from 'rxjs';

const FACILITIES_DATA: Facility[] = [
  {
    codigo_cnes: 19046,
    numero_cnpj_entidade: null,
    nome_razao_social: 'LABORATORIO SANTA MARIA LTDA SC',
    nome_fantasia: 'LABORATORIO SANTA MARIA',
    natureza_organizacao_entidade: null,
    tipo_gestao: 'M',
    descricao_nivel_hierarquia: null,
    descricao_esfera_administrativa: null,
    codigo_tipo_unidade: 39,
    codigo_cep_estabelecimento: '83005000',
    endereco_estabelecimento: 'RUA XV DE NOVEMBRO',
    numero_estabelecimento: '2061',
    bairro_estabelecimento: 'CENTRO',
    numero_telefone_estabelecimento: '(41) 3382 - 1327',
    latitude_estabelecimento_decimo_grau: -25.5385499402498,
    longitude_estabelecimento_decimo_grau: -49.1988882422447,
    endereco_email_estabelecimento: 'labsanta@bol.com.br',
    numero_cnpj: '81311995000103',
    codigo_identificador_turno_atendimento: '03',
    descricao_turno_atendimento: 'ATENDIMENTOS NOS TURNOS DA MANHA E A TARDE',
    estabelecimento_faz_atendimento_ambulatorial_sus: 'NAO',
    codigo_estabelecimento_saude: '4125500019046',
    codigo_uf: 41,
    codigo_municipio: 412550,
    descricao_natureza_juridica_estabelecimento: '2240',
    codigo_motivo_desabilitacao_estabelecimento: '04',
    estabelecimento_possui_centro_cirurgico: 0,
    estabelecimento_possui_centro_obstetrico: 0,
    estabelecimento_possui_centro_neonatal: 0,
    estabelecimento_possui_atendimento_hospitalar: 0,
    estabelecimento_possui_servico_apoio: 1,
    estabelecimento_possui_atendimento_ambulatorial: 0,
    codigo_atividade_ensino_unidade: '04',
    codigo_natureza_organizacao_unidade: null,
    codigo_nivel_hierarquia_unidade: null,
    codigo_esfera_administrativa_unidade: null,
  },
  {
    codigo_cnes: 647,
    numero_cnpj_entidade: '10565000000192',
    nome_razao_social: 'PREFEITURA DA CIDADE DO RECIFE',
    nome_fantasia: 'US 144 POLICLINICA CLEMENTINO FRAGA',
    natureza_organizacao_entidade: null,
    tipo_gestao: 'M',
    descricao_nivel_hierarquia: null,
    descricao_esfera_administrativa: null,
    codigo_tipo_unidade: 4,
    codigo_cep_estabelecimento: '52280510',
    endereco_estabelecimento: 'RUA JAPARATUBA',
    numero_estabelecimento: '260',
    bairro_estabelecimento: 'VASCO DA GAMA',
    numero_telefone_estabelecimento: '(81) 33556048-6049',
    latitude_estabelecimento_decimo_grau: -8.01941185,
    longitude_estabelecimento_decimo_grau: -34.919800228028,
    endereco_email_estabelecimento: 'CLEMENTINOCFRAGA@GMAIL.COM',
    numero_cnpj: null,
    codigo_identificador_turno_atendimento: '04',
    descricao_turno_atendimento:
      'ATENDIMENTO NOS TURNOS DA MANHA, TARDE E NOITE',
    estabelecimento_faz_atendimento_ambulatorial_sus: 'SIM',
    codigo_estabelecimento_saude: '2611600000647',
    codigo_uf: 26,
    codigo_municipio: 261160,
    descricao_natureza_juridica_estabelecimento: '1244',
    codigo_motivo_desabilitacao_estabelecimento: null,
    estabelecimento_possui_centro_cirurgico: 0,
    estabelecimento_possui_centro_obstetrico: 0,
    estabelecimento_possui_centro_neonatal: 0,
    estabelecimento_possui_atendimento_hospitalar: 0,
    estabelecimento_possui_servico_apoio: 1,
    estabelecimento_possui_atendimento_ambulatorial: 0,
    codigo_atividade_ensino_unidade: '04',
    codigo_natureza_organizacao_unidade: null,
    codigo_nivel_hierarquia_unidade: null,
    codigo_esfera_administrativa_unidade: null,
  },
  {
    codigo_cnes: 19690,
    numero_cnpj_entidade: '82892282000143',
    nome_razao_social: 'PREF MUN FLORIANOPOLIS SMS FMS',
    nome_fantasia: 'CS PANTANAL',
    natureza_organizacao_entidade: null,
    tipo_gestao: 'M',
    descricao_nivel_hierarquia: null,
    descricao_esfera_administrativa: null,
    codigo_tipo_unidade: 2,
    codigo_cep_estabelecimento: '88040000',
    endereco_estabelecimento: 'RUA DEPUTADO ANTONIO EDU VIEIRA',
    numero_estabelecimento: '855',
    bairro_estabelecimento: 'PANTANAL',
    numero_telefone_estabelecimento: '(48) 32382232',
    latitude_estabelecimento_decimo_grau: -27.607919,
    longitude_estabelecimento_decimo_grau: -48.520108,
    endereco_email_estabelecimento: 'cspantanal.coord@gmail.com',
    numero_cnpj: null,
    codigo_identificador_turno_atendimento: '03',
    descricao_turno_atendimento: 'ATENDIMENTOS NOS TURNOS DA MANHA E A TARDE',
    estabelecimento_faz_atendimento_ambulatorial_sus: 'SIM',
    codigo_estabelecimento_saude: '4205400019690',
    codigo_uf: 42,
    codigo_municipio: 420540,
    descricao_natureza_juridica_estabelecimento: '1244',
    codigo_motivo_desabilitacao_estabelecimento: null,
    estabelecimento_possui_centro_cirurgico: 0,
    estabelecimento_possui_centro_obstetrico: 0,
    estabelecimento_possui_centro_neonatal: 0,
    estabelecimento_possui_atendimento_hospitalar: 0,
    estabelecimento_possui_servico_apoio: 1,
    estabelecimento_possui_atendimento_ambulatorial: 0,
    codigo_atividade_ensino_unidade: '04',
    codigo_natureza_organizacao_unidade: null,
    codigo_nivel_hierarquia_unidade: null,
    codigo_esfera_administrativa_unidade: null,
  },
  {
    codigo_cnes: 447072,
    numero_cnpj_entidade: '03507548000110',
    nome_razao_social: 'PREFEITURA MUNICIPAL DE VARZEA GRANDE',
    nome_fantasia: 'ESF CABO MICHEL',
    natureza_organizacao_entidade: null,
    tipo_gestao: 'M',
    descricao_nivel_hierarquia: null,
    descricao_esfera_administrativa: null,
    codigo_tipo_unidade: 2,
    codigo_cep_estabelecimento: '78158124',
    endereco_estabelecimento: 'NOVA OLIMPIA',
    numero_estabelecimento: 'S/N',
    bairro_estabelecimento: 'CABO MICHEL',
    numero_telefone_estabelecimento: null,
    latitude_estabelecimento_decimo_grau: -15.647,
    longitude_estabelecimento_decimo_grau: -56.133,
    endereco_email_estabelecimento: 'ubsvgcbmichel@gmal.com',
    numero_cnpj: null,
    codigo_identificador_turno_atendimento: '03',
    descricao_turno_atendimento: 'ATENDIMENTOS NOS TURNOS DA MANHA E A TARDE',
    estabelecimento_faz_atendimento_ambulatorial_sus: 'SIM',
    codigo_estabelecimento_saude: '5108400447072',
    codigo_uf: 51,
    codigo_municipio: 510840,
    descricao_natureza_juridica_estabelecimento: '1244',
    codigo_motivo_desabilitacao_estabelecimento: null,
    estabelecimento_possui_centro_cirurgico: 0,
    estabelecimento_possui_centro_obstetrico: 0,
    estabelecimento_possui_centro_neonatal: 0,
    estabelecimento_possui_atendimento_hospitalar: 0,
    estabelecimento_possui_servico_apoio: 1,
    estabelecimento_possui_atendimento_ambulatorial: 0,
    codigo_atividade_ensino_unidade: '04',
    codigo_natureza_organizacao_unidade: null,
    codigo_nivel_hierarquia_unidade: null,
    codigo_esfera_administrativa_unidade: null,
  },
  {
    codigo_cnes: 490091,
    numero_cnpj_entidade: '87613626000151',
    nome_razao_social: 'PREFEITURA MUNICIPAL DE LAGOA VERMELHA',
    nome_fantasia: 'PRESIDIO ESTADUAL DE LAGOA VERMELHA',
    natureza_organizacao_entidade: null,
    tipo_gestao: 'M',
    descricao_nivel_hierarquia: null,
    descricao_esfera_administrativa: null,
    codigo_tipo_unidade: 2,
    codigo_cep_estabelecimento: '95300000',
    endereco_estabelecimento: 'PRESIDENTE VARGAS',
    numero_estabelecimento: '4172',
    bairro_estabelecimento: 'FLORESTA',
    numero_telefone_estabelecimento: '(54)33581962',
    latitude_estabelecimento_decimo_grau: -28.219256134472,
    longitude_estabelecimento_decimo_grau: -51.5153646469116,
    endereco_email_estabelecimento: null,
    numero_cnpj: null,
    codigo_identificador_turno_atendimento: '03',
    descricao_turno_atendimento: 'ATENDIMENTOS NOS TURNOS DA MANHA E A TARDE',
    estabelecimento_faz_atendimento_ambulatorial_sus: 'SIM',
    codigo_estabelecimento_saude: '4311300490091',
    codigo_uf: 43,
    codigo_municipio: 431130,
    descricao_natureza_juridica_estabelecimento: '1244',
    codigo_motivo_desabilitacao_estabelecimento: null,
    estabelecimento_possui_centro_cirurgico: 0,
    estabelecimento_possui_centro_obstetrico: 0,
    estabelecimento_possui_centro_neonatal: 0,
    estabelecimento_possui_atendimento_hospitalar: 0,
    estabelecimento_possui_servico_apoio: 0,
    estabelecimento_possui_atendimento_ambulatorial: 0,
    codigo_atividade_ensino_unidade: '04',
    codigo_natureza_organizacao_unidade: null,
    codigo_nivel_hierarquia_unidade: null,
    codigo_esfera_administrativa_unidade: null,
  },
];

@Injectable({
  providedIn: 'root',
})
export class FacilityService {
  private API_URL =
    'https://apidadosabertos.saude.gov.br/cnes/estabelecimentos';

  constructor(private http: HttpClient) {}
  getFacilities(): Observable<FacilityResponse> {
    return this.http.get<FacilityResponse>(this.API_URL);
    //return of(FACILITIES_DATA);
  }

  getFacilityInfoByCnes(cnes: number): Observable<Facility> {
    return this.http.get<Facility>(`${this.API_URL}/${cnes}`);
    /*const facility = FACILITIES_DATA.find((f) => f.codigo_cnes === cnes);
    return facility
      ? of(facility)
      : throwError(
          () =>
            new Error(
              `Não foi encontrado nenhum estabelecimento com esse CNES: ${cnes}`
            )
        );*/
  }
}
